"""initial schema

Revision ID: 1a68584ec3b2
Revises: 
Create Date: 2026-05-16 16:04:43.932075+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1a68584ec3b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('actor_agent_id', sa.String(length=255), nullable=False),
    sa.Column('actor_session_id', sa.String(length=255), nullable=False),
    sa.Column('actor_run_id', sa.String(length=255), nullable=True),
    sa.Column('actor_user_id', sa.String(length=255), nullable=True),
    sa.Column('actor_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'BLOCKED', 'PENDING_APPROVAL', 'FAILED', 'REPLAYED', name='transaction_status'), nullable=False),
    sa.Column('execution_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_actor_agent_id'), 'transactions', ['actor_agent_id'], unique=False)
    op.create_index(op.f('ix_transactions_actor_session_id'), 'transactions', ['actor_session_id'], unique=False)
    op.create_index(op.f('ix_transactions_actor_tenant_id'), 'transactions', ['actor_tenant_id'], unique=False)
    op.create_index(op.f('ix_transactions_actor_user_id'), 'transactions', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_started_at'), 'transactions', ['started_at'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_tool_call_id'), 'transactions', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_transactions_tool_name'), 'transactions', ['tool_name'], unique=False)
    op.create_index(op.f('ix_transactions_trace_id'), 'transactions', ['trace_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('sequence_num', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('TRANSACTION_STARTED', 'GATE_EVALUATED', 'TOOL_DRY_RUN', 'TOOL_EXECUTED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_DENIED', 'APPROVAL_TIMEOUT', 'IDEMPOTENCY_HIT', 'TRANSACTION_COMPLETED', 'TRANSACTION_FAILED', name='audit_event_type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_index('ix_audit_tx_sequence', 'audit_events', ['transaction_id', 'sequence_num'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_tx_sequence', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_transaction_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_transactions_trace_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tool_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tool_call_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_started_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_actor_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_actor_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_actor_session_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_actor_agent_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
