"""add approvals table

Revision ID: 60810c3c7c5d
Revises: 1a68584ec3b2
Create Date: 2026-05-16 17:04:27.010637+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60810c3c7c5d'
down_revision: Union[str, None] = '1a68584ec3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('actor_agent_id', sa.String(length=255), nullable=False),
    sa.Column('requested_reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GRANTED', 'DENIED', 'EXPIRED', name='approval_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_actor_agent_id'), 'approvals', ['actor_agent_id'], unique=False)
    op.create_index(op.f('ix_approvals_fingerprint'), 'approvals', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_approvals_requested_at'), 'approvals', ['requested_at'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_tool_name'), 'approvals', ['tool_name'], unique=False)
    op.create_index(op.f('ix_approvals_transaction_id'), 'approvals', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_transaction_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_tool_name'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_requested_at'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_fingerprint'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_actor_agent_id'), table_name='approvals')
    op.drop_table('approvals')
    # autogenerate doesn't drop named Postgres enums — do it explicitly
    sa.Enum(name='approval_status').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
